version: '3.8'

volumes:
  datafiles:

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_HOST=mysql
    restart: always
    ports:
     - 81:80

    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.0
    container_name: mysql
    #build:
     # context: .
      #dockerfile: dockerfile

    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_TCP_PORT=3306
    volumes:
      - datafiles:/var/lib/mysql
    restart: always

  website:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_DBHOST=mysql
      - MYSQL_DBPORT=3306
      - MYSQL_DBUSER=root
      - MYSQL_DBPASS=secret
      #- MYSQL_DBNAME=
    links:
      - mysql
    ports:
      - 8026:80
    depends_on:
      - mysql  
